export type DoencaVeterinariaCatalogo = {
  nome: string;
  especie:
    | "CANINO"
    | "FELINO"
    | "AMBOS";
  categoria: string;
  sinonimos: string;
};

export const CATALOGO_DOENCAS_CAES_GATOS: DoencaVeterinariaCatalogo[] = [
  {
    nome: "Cinomose",
    especie: "CANINO",
    categoria: "Infectocontagiosa",
    sinonimos: "distemper; doença de Carré",
  },
  {
    nome: "Parvovirose canina",
    especie: "CANINO",
    categoria: "Infectocontagiosa",
    sinonimos: "parvovírus canino; CPV",
  },
  {
    nome: "Coronavirose entérica canina",
    especie: "CANINO",
    categoria: "Infectocontagiosa",
    sinonimos: "coronavírus entérico canino; CCoV",
  },
  {
    nome: "Hepatite infecciosa canina",
    especie: "CANINO",
    categoria: "Infectocontagiosa",
    sinonimos: "adenovírus canino tipo 1; CAV-1",
  },
  {
    nome: "Traqueobronquite infecciosa canina",
    especie: "CANINO",
    categoria: "Respiratória/Infectocontagiosa",
    sinonimos: "tosse dos canis; complexo respiratório infeccioso canino",
  },
  {
    nome: "Leptospirose",
    especie: "AMBOS",
    categoria: "Infectocontagiosa",
    sinonimos: "Leptospira",
  },
  {
    nome: "Raiva",
    especie: "AMBOS",
    categoria: "Infectocontagiosa",
    sinonimos: "rabies",
  },
  {
    nome: "Brucelose canina",
    especie: "CANINO",
    categoria: "Infectocontagiosa",
    sinonimos: "Brucella canis",
  },
  {
    nome: "Erliquiose canina",
    especie: "CANINO",
    categoria: "Hemoparasitária",
    sinonimos: "Ehrlichia canis",
  },
  {
    nome: "Anaplasmose",
    especie: "AMBOS",
    categoria: "Hemoparasitária",
    sinonimos: "Anaplasma",
  },
  {
    nome: "Babesiose",
    especie: "AMBOS",
    categoria: "Hemoparasitária",
    sinonimos: "Babesia",
  },
  {
    nome: "Hepatozoonose canina",
    especie: "CANINO",
    categoria: "Hemoparasitária",
    sinonimos: "Hepatozoon canis",
  },
  {
    nome: "Leishmaniose visceral canina",
    especie: "CANINO",
    categoria: "Infectocontagiosa",
    sinonimos: "leishmaniose; LVC",
  },
  {
    nome: "Bartonelose",
    especie: "AMBOS",
    categoria: "Infectocontagiosa",
    sinonimos: "Bartonella",
  },
  {
    nome: "Toxoplasmose",
    especie: "AMBOS",
    categoria: "Protozoária",
    sinonimos: "Toxoplasma gondii",
  },
  {
    nome: "Neosporose",
    especie: "CANINO",
    categoria: "Protozoária",
    sinonimos: "Neospora caninum",
  },
  {
    nome: "Giardíase",
    especie: "AMBOS",
    categoria: "Parasitária",
    sinonimos: "Giardia",
  },
  {
    nome: "Coccidiose intestinal",
    especie: "AMBOS",
    categoria: "Parasitária",
    sinonimos: "Cystoisospora; Isospora",
  },
  {
    nome: "Criptosporidiose",
    especie: "AMBOS",
    categoria: "Parasitária",
    sinonimos: "Cryptosporidium",
  },
  {
    nome: "Tricuríase",
    especie: "CANINO",
    categoria: "Parasitária",
    sinonimos: "Trichuris vulpis",
  },
  {
    nome: "Ancilostomíase",
    especie: "AMBOS",
    categoria: "Parasitária",
    sinonimos: "Ancylostoma",
  },
  {
    nome: "Toxocaríase",
    especie: "AMBOS",
    categoria: "Parasitária",
    sinonimos: "Toxocara",
  },
  {
    nome: "Dipilidiose",
    especie: "AMBOS",
    categoria: "Parasitária",
    sinonimos: "Dipylidium caninum",
  },
  {
    nome: "Dirofilariose",
    especie: "AMBOS",
    categoria: "Cardiopulmonar/Parasitária",
    sinonimos: "verme do coração; Dirofilaria immitis",
  },
  {
    nome: "Angiostrongilose",
    especie: "CANINO",
    categoria: "Respiratória/Parasitária",
    sinonimos: "Angiostrongylus vasorum",
  },
  {
    nome: "Aelurostrongilose",
    especie: "FELINO",
    categoria: "Respiratória/Parasitária",
    sinonimos: "Aelurostrongylus abstrusus",
  },
  {
    nome: "Esporotricose",
    especie: "AMBOS",
    categoria: "Fúngica",
    sinonimos: "Sporothrix",
  },
  {
    nome: "Dermatofitose",
    especie: "AMBOS",
    categoria: "Fúngica/Dermatológica",
    sinonimos: "micose; Microsporum; Trichophyton",
  },
  {
    nome: "Criptococose",
    especie: "AMBOS",
    categoria: "Fúngica",
    sinonimos: "Cryptococcus",
  },
  {
    nome: "Histoplasmose",
    especie: "AMBOS",
    categoria: "Fúngica",
    sinonimos: "Histoplasma",
  },
  {
    nome: "Blastomicose",
    especie: "AMBOS",
    categoria: "Fúngica",
    sinonimos: "Blastomyces",
  },
  {
    nome: "FeLV",
    especie: "FELINO",
    categoria: "Infectocontagiosa",
    sinonimos: "leucemia viral felina; vírus da leucemia felina",
  },
  {
    nome: "FIV",
    especie: "FELINO",
    categoria: "Infectocontagiosa",
    sinonimos: "imunodeficiência viral felina; AIDS felina",
  },
  {
    nome: "Panleucopenia felina",
    especie: "FELINO",
    categoria: "Infectocontagiosa",
    sinonimos: "parvovirose felina",
  },
  {
    nome: "Herpesvírus felino",
    especie: "FELINO",
    categoria: "Respiratória/Infectocontagiosa",
    sinonimos: "rinotraqueíte viral felina; FHV-1",
  },
  {
    nome: "Calicivirose felina",
    especie: "FELINO",
    categoria: "Respiratória/Infectocontagiosa",
    sinonimos: "calicivírus felino; FCV",
  },
  {
    nome: "PIF",
    especie: "FELINO",
    categoria: "Infectocontagiosa",
    sinonimos: "peritonite infecciosa felina",
  },
  {
    nome: "Clamidiose felina",
    especie: "FELINO",
    categoria: "Oftálmica/Infectocontagiosa",
    sinonimos: "Chlamydia felis",
  },
  {
    nome: "Micoplasmose hemotrópica felina",
    especie: "FELINO",
    categoria: "Hemoparasitária",
    sinonimos: "hemoplasmose felina; Mycoplasma haemofelis",
  },
  {
    nome: "Dermatite atópica",
    especie: "AMBOS",
    categoria: "Dermatológica",
    sinonimos: "atopia; dermatite alérgica",
  },
  {
    nome: "Dermatite alérgica à picada de pulga",
    especie: "AMBOS",
    categoria: "Dermatológica",
    sinonimos: "DAPP; alergia à pulga",
  },
  {
    nome: "Alergia alimentar",
    especie: "AMBOS",
    categoria: "Dermatológica/Gastrointestinal",
    sinonimos: "hipersensibilidade alimentar",
  },
  {
    nome: "Piodermite superficial",
    especie: "CANINO",
    categoria: "Dermatológica",
    sinonimos: "foliculite bacteriana superficial",
  },
  {
    nome: "Piodermite profunda",
    especie: "CANINO",
    categoria: "Dermatológica",
    sinonimos: "furunculose bacteriana",
  },
  {
    nome: "Malasseziose cutânea",
    especie: "AMBOS",
    categoria: "Dermatológica",
    sinonimos: "dermatite por Malassezia",
  },
  {
    nome: "Demodicose",
    especie: "AMBOS",
    categoria: "Dermatológica/Parasitária",
    sinonimos: "sarna demodécica; Demodex",
  },
  {
    nome: "Escabiose",
    especie: "AMBOS",
    categoria: "Dermatológica/Parasitária",
    sinonimos: "sarna sarcóptica; Sarcoptes",
  },
  {
    nome: "Notoedrose",
    especie: "FELINO",
    categoria: "Dermatológica/Parasitária",
    sinonimos: "sarna notoédrica; Notoedres",
  },
  {
    nome: "Cheyletiellose",
    especie: "AMBOS",
    categoria: "Dermatológica/Parasitária",
    sinonimos: "Cheyletiella",
  },
  {
    nome: "Pediculose",
    especie: "AMBOS",
    categoria: "Dermatológica/Parasitária",
    sinonimos: "piolhos",
  },
  {
    nome: "Dermatite por contato",
    especie: "AMBOS",
    categoria: "Dermatológica",
    sinonimos: "dermatite de contato",
  },
  {
    nome: "Dermatite acral por lambedura",
    especie: "CANINO",
    categoria: "Dermatológica",
    sinonimos: "granuloma de lambedura",
  },
  {
    nome: "Complexo granuloma eosinofílico felino",
    especie: "FELINO",
    categoria: "Dermatológica",
    sinonimos: "granuloma eosinofílico; placa eosinofílica",
  },
  {
    nome: "Acne felina",
    especie: "FELINO",
    categoria: "Dermatológica",
    sinonimos: "acne de queixo",
  },
  {
    nome: "Alopecia psicogênica felina",
    especie: "FELINO",
    categoria: "Dermatológica/Comportamental",
    sinonimos: "alopecia por lambedura",
  },
  {
    nome: "Otite externa",
    especie: "AMBOS",
    categoria: "Otológica",
    sinonimos: "inflamação de ouvido externo",
  },
  {
    nome: "Otite média",
    especie: "AMBOS",
    categoria: "Otológica",
    sinonimos: "inflamação de ouvido médio",
  },
  {
    nome: "Otite interna",
    especie: "AMBOS",
    categoria: "Otológica/Neurológica",
    sinonimos: "labirintite",
  },
  {
    nome: "Otoacaríase",
    especie: "AMBOS",
    categoria: "Otológica/Parasitária",
    sinonimos: "Otodectes cynotis; ácaro de ouvido",
  },
  {
    nome: "Hematoma auricular",
    especie: "AMBOS",
    categoria: "Otológica",
    sinonimos: "otohematoma",
  },
  {
    nome: "Gastrite",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "inflamação gástrica",
  },
  {
    nome: "Gastroenterite aguda",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "enterite aguda",
  },
  {
    nome: "Enteropatia crônica",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "doença inflamatória intestinal; DII",
  },
  {
    nome: "Colite",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "inflamação de cólon",
  },
  {
    nome: "Constipação",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "prisão de ventre",
  },
  {
    nome: "Megacólon",
    especie: "FELINO",
    categoria: "Gastrointestinal",
    sinonimos: "megacolon",
  },
  {
    nome: "Obstrução gastrointestinal por corpo estranho",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "corpo estranho gastrointestinal",
  },
  {
    nome: "Intussuscepção",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "invaginação intestinal",
  },
  {
    nome: "Dilatação-vólvulo gástrico",
    especie: "CANINO",
    categoria: "Gastrointestinal/Emergência",
    sinonimos: "torção gástrica; DVG",
  },
  {
    nome: "Pancreatite",
    especie: "AMBOS",
    categoria: "Pancreática",
    sinonimos: "inflamação pancreática",
  },
  {
    nome: "Insuficiência pancreática exócrina",
    especie: "CANINO",
    categoria: "Pancreática",
    sinonimos: "IPE",
  },
  {
    nome: "Colangite felina",
    especie: "FELINO",
    categoria: "Hepatobiliar",
    sinonimos: "colangio-hepatite felina",
  },
  {
    nome: "Lipidose hepática felina",
    especie: "FELINO",
    categoria: "Hepatobiliar",
    sinonimos: "esteatose hepática felina",
  },
  {
    nome: "Hepatite crônica",
    especie: "CANINO",
    categoria: "Hepatobiliar",
    sinonimos: "hepatopatia inflamatória crônica",
  },
  {
    nome: "Hepatopatia por acúmulo de cobre",
    especie: "CANINO",
    categoria: "Hepatobiliar",
    sinonimos: "hepatopatia associada ao cobre",
  },
  {
    nome: "Shunt portossistêmico",
    especie: "AMBOS",
    categoria: "Hepatobiliar/Congênita",
    sinonimos: "desvio portossistêmico; PSS",
  },
  {
    nome: "Doença da vesícula biliar",
    especie: "AMBOS",
    categoria: "Hepatobiliar",
    sinonimos: "colecistopatia",
  },
  {
    nome: "Mucocele de vesícula biliar",
    especie: "CANINO",
    categoria: "Hepatobiliar",
    sinonimos: "mucocele biliar",
  },
  {
    nome: "Peritonite",
    especie: "AMBOS",
    categoria: "Gastrointestinal",
    sinonimos: "inflamação peritoneal",
  },
  {
    nome: "Diabetes mellitus",
    especie: "AMBOS",
    categoria: "Endócrina",
    sinonimos: "diabetes",
  },
  {
    nome: "Cetoacidose diabética",
    especie: "AMBOS",
    categoria: "Endócrina/Emergência",
    sinonimos: "CAD",
  },
  {
    nome: "Hipotireoidismo",
    especie: "CANINO",
    categoria: "Endócrina",
    sinonimos: "hipofunção tireoidiana",
  },
  {
    nome: "Hipertireoidismo felino",
    especie: "FELINO",
    categoria: "Endócrina",
    sinonimos: "hiperfunção tireoidiana",
  },
  {
    nome: "Hiperadrenocorticismo",
    especie: "CANINO",
    categoria: "Endócrina",
    sinonimos: "síndrome de Cushing; Cushing",
  },
  {
    nome: "Hipoadrenocorticismo",
    especie: "CANINO",
    categoria: "Endócrina",
    sinonimos: "doença de Addison; Addison",
  },
  {
    nome: "Hiperparatireoidismo",
    especie: "AMBOS",
    categoria: "Endócrina",
    sinonimos: "hiperparatireoidismo primário",
  },
  {
    nome: "Hipoparatireoidismo",
    especie: "AMBOS",
    categoria: "Endócrina",
    sinonimos: "hipoparatireoidismo primário",
  },
  {
    nome: "Obesidade",
    especie: "AMBOS",
    categoria: "Metabólica",
    sinonimos: "excesso de peso",
  },
  {
    nome: "Hipoglicemia",
    especie: "AMBOS",
    categoria: "Metabólica",
    sinonimos: "glicose baixa",
  },
  {
    nome: "Hipercalcemia",
    especie: "AMBOS",
    categoria: "Metabólica",
    sinonimos: "cálcio elevado",
  },
  {
    nome: "Hipocalcemia puerperal",
    especie: "CANINO",
    categoria: "Metabólica/Reprodutiva",
    sinonimos: "eclâmpsia puerperal",
  },
  {
    nome: "Doença renal crônica",
    especie: "AMBOS",
    categoria: "Renal",
    sinonimos: "DRC; insuficiência renal crônica",
  },
  {
    nome: "Lesão renal aguda",
    especie: "AMBOS",
    categoria: "Renal",
    sinonimos: "LRA; insuficiência renal aguda",
  },
  {
    nome: "Glomerulopatia",
    especie: "AMBOS",
    categoria: "Renal",
    sinonimos: "doença glomerular",
  },
  {
    nome: "Pielonefrite",
    especie: "AMBOS",
    categoria: "Renal/Urinária",
    sinonimos: "infecção renal",
  },
  {
    nome: "Cistite bacteriana",
    especie: "AMBOS",
    categoria: "Urinária",
    sinonimos: "infecção urinária baixa",
  },
  {
    nome: "Cistite idiopática felina",
    especie: "FELINO",
    categoria: "Urinária",
    sinonimos: "CIF",
  },
  {
    nome: "Doença do trato urinário inferior dos felinos",
    especie: "FELINO",
    categoria: "Urinária",
    sinonimos: "DTUIF; FLUTD",
  },
  {
    nome: "Urolitíase",
    especie: "AMBOS",
    categoria: "Urinária",
    sinonimos: "cálculo urinário; litíase urinária",
  },
  {
    nome: "Obstrução uretral",
    especie: "AMBOS",
    categoria: "Urinária/Emergência",
    sinonimos: "obstrução urinária",
  },
  {
    nome: "Incontinência urinária",
    especie: "AMBOS",
    categoria: "Urinária",
    sinonimos: "incompetência do esfíncter uretral",
  },
  {
    nome: "Doença prostática benigna",
    especie: "CANINO",
    categoria: "Urinária/Reprodutiva",
    sinonimos: "hiperplasia prostática benigna; HPB",
  },
  {
    nome: "Prostatite",
    especie: "CANINO",
    categoria: "Urinária/Reprodutiva",
    sinonimos: "inflamação da próstata",
  },
  {
    nome: "Doença valvar degenerativa mitral",
    especie: "CANINO",
    categoria: "Cardiovascular",
    sinonimos: "endocardiose mitral; doença mixomatosa da valva mitral; DMVM",
  },
  {
    nome: "Cardiomiopatia dilatada",
    especie: "CANINO",
    categoria: "Cardiovascular",
    sinonimos: "CMD",
  },
  {
    nome: "Cardiomiopatia hipertrófica",
    especie: "FELINO",
    categoria: "Cardiovascular",
    sinonimos: "CMH",
  },
  {
    nome: "Cardiomiopatia restritiva",
    especie: "FELINO",
    categoria: "Cardiovascular",
    sinonimos: "CMR",
  },
  {
    nome: "Cardiomiopatia arritmogênica do ventrículo direito",
    especie: "CANINO",
    categoria: "Cardiovascular",
    sinonimos: "CAVD",
  },
  {
    nome: "Insuficiência cardíaca congestiva",
    especie: "AMBOS",
    categoria: "Cardiovascular",
    sinonimos: "ICC",
  },
  {
    nome: "Hipertensão arterial sistêmica",
    especie: "AMBOS",
    categoria: "Cardiovascular",
    sinonimos: "hipertensão",
  },
  {
    nome: "Hipertensão pulmonar",
    especie: "AMBOS",
    categoria: "Cardiovascular",
    sinonimos: "pressão pulmonar elevada",
  },
  {
    nome: "Estenose pulmonar",
    especie: "CANINO",
    categoria: "Cardiovascular/Congênita",
    sinonimos: "estenose da pulmonar",
  },
  {
    nome: "Estenose subaórtica",
    especie: "CANINO",
    categoria: "Cardiovascular/Congênita",
    sinonimos: "estenose aórtica subvalvar",
  },
  {
    nome: "Persistência do ducto arterioso",
    especie: "AMBOS",
    categoria: "Cardiovascular/Congênita",
    sinonimos: "PDA; ducto arterioso patente",
  },
  {
    nome: "Defeito do septo ventricular",
    especie: "AMBOS",
    categoria: "Cardiovascular/Congênita",
    sinonimos: "DSV",
  },
  {
    nome: "Defeito do septo atrial",
    especie: "AMBOS",
    categoria: "Cardiovascular/Congênita",
    sinonimos: "DSA",
  },
  {
    nome: "Tromboembolismo arterial felino",
    especie: "FELINO",
    categoria: "Cardiovascular/Emergência",
    sinonimos: "tromboembolismo aórtico; sela aórtica",
  },
  {
    nome: "Arritmia cardíaca",
    especie: "AMBOS",
    categoria: "Cardiovascular",
    sinonimos: "distúrbio do ritmo cardíaco",
  },
  {
    nome: "Bronquite crônica",
    especie: "AMBOS",
    categoria: "Respiratória",
    sinonimos: "bronquite",
  },
  {
    nome: "Asma felina",
    especie: "FELINO",
    categoria: "Respiratória",
    sinonimos: "bronquite alérgica felina",
  },
  {
    nome: "Pneumonia bacteriana",
    especie: "AMBOS",
    categoria: "Respiratória",
    sinonimos: "broncopneumonia bacteriana",
  },
  {
    nome: "Pneumonia aspirativa",
    especie: "AMBOS",
    categoria: "Respiratória",
    sinonimos: "broncoaspiração",
  },
  {
    nome: "Edema pulmonar",
    especie: "AMBOS",
    categoria: "Respiratória/Cardiovascular",
    sinonimos: "edema de pulmão",
  },
  {
    nome: "Colapso de traqueia",
    especie: "CANINO",
    categoria: "Respiratória",
    sinonimos: "colapso traqueal",
  },
  {
    nome: "Síndrome respiratória dos braquicefálicos",
    especie: "CANINO",
    categoria: "Respiratória",
    sinonimos: "síndrome braquicefálica",
  },
  {
    nome: "Paralisia de laringe",
    especie: "CANINO",
    categoria: "Respiratória/Neurológica",
    sinonimos: "paralisia laríngea",
  },
  {
    nome: "Efusão pleural",
    especie: "AMBOS",
    categoria: "Respiratória",
    sinonimos: "derrame pleural",
  },
  {
    nome: "Pneumotórax",
    especie: "AMBOS",
    categoria: "Respiratória/Emergência",
    sinonimos: "ar no espaço pleural",
  },
  {
    nome: "Rinite crônica",
    especie: "AMBOS",
    categoria: "Respiratória",
    sinonimos: "rinite",
  },
  {
    nome: "Pólipo nasofaríngeo felino",
    especie: "FELINO",
    categoria: "Respiratória/Otológica",
    sinonimos: "pólipo nasofaríngeo",
  },
  {
    nome: "Epilepsia idiopática",
    especie: "AMBOS",
    categoria: "Neurológica",
    sinonimos: "epilepsia",
  },
  {
    nome: "Estado epiléptico",
    especie: "AMBOS",
    categoria: "Neurológica/Emergência",
    sinonimos: "status epilepticus",
  },
  {
    nome: "Doença do disco intervertebral",
    especie: "AMBOS",
    categoria: "Neurológica/Ortopédica",
    sinonimos: "DDIV; hérnia de disco",
  },
  {
    nome: "Síndrome vestibular periférica",
    especie: "AMBOS",
    categoria: "Neurológica",
    sinonimos: "doença vestibular periférica",
  },
  {
    nome: "Síndrome vestibular central",
    especie: "AMBOS",
    categoria: "Neurológica",
    sinonimos: "doença vestibular central",
  },
  {
    nome: "Meningoencefalite",
    especie: "AMBOS",
    categoria: "Neurológica",
    sinonimos: "encefalite; meningite",
  },
  {
    nome: "Meningoencefalite de origem desconhecida",
    especie: "CANINO",
    categoria: "Neurológica",
    sinonimos: "MUO; meningoencefalite não infecciosa",
  },
  {
    nome: "Disfunção cognitiva",
    especie: "AMBOS",
    categoria: "Neurológica/Geriátrica",
    sinonimos: "síndrome de disfunção cognitiva",
  },
  {
    nome: "Neuropatia periférica",
    especie: "AMBOS",
    categoria: "Neurológica",
    sinonimos: "polineuropatia",
  },
  {
    nome: "Miastenia gravis",
    especie: "AMBOS",
    categoria: "Neuromuscular",
    sinonimos: "miastenia",
  },
  {
    nome: "Polirradiculoneurite",
    especie: "CANINO",
    categoria: "Neuromuscular",
    sinonimos: "coonhound paralysis",
  },
  {
    nome: "Osteoartrite",
    especie: "AMBOS",
    categoria: "Ortopédica",
    sinonimos: "artrose; doença articular degenerativa",
  },
  {
    nome: "Displasia coxofemoral",
    especie: "CANINO",
    categoria: "Ortopédica",
    sinonimos: "displasia de quadril",
  },
  {
    nome: "Displasia de cotovelo",
    especie: "CANINO",
    categoria: "Ortopédica",
    sinonimos: "displasia do cotovelo",
  },
  {
    nome: "Ruptura do ligamento cruzado cranial",
    especie: "CANINO",
    categoria: "Ortopédica",
    sinonimos: "RLCC; ruptura de cruzado",
  },
  {
    nome: "Luxação patelar",
    especie: "CANINO",
    categoria: "Ortopédica",
    sinonimos: "luxação de patela",
  },
  {
    nome: "Luxação coxofemoral",
    especie: "AMBOS",
    categoria: "Ortopédica",
    sinonimos: "luxação de quadril",
  },
  {
    nome: "Osteocondrite dissecante",
    especie: "CANINO",
    categoria: "Ortopédica",
    sinonimos: "OCD",
  },
  {
    nome: "Panosteíte",
    especie: "CANINO",
    categoria: "Ortopédica",
    sinonimos: "panosteite eosinofílica",
  },
  {
    nome: "Osteomielite",
    especie: "AMBOS",
    categoria: "Ortopédica/Infectocontagiosa",
    sinonimos: "infecção óssea",
  },
  {
    nome: "Fratura óssea",
    especie: "AMBOS",
    categoria: "Ortopédica/Trauma",
    sinonimos: "fratura",
  },
  {
    nome: "Conjuntivite",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "inflamação conjuntival",
  },
  {
    nome: "Ceratoconjuntivite seca",
    especie: "CANINO",
    categoria: "Oftálmica",
    sinonimos: "olho seco; KCS",
  },
  {
    nome: "Úlcera de córnea",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "úlcera corneana",
  },
  {
    nome: "Ceratite",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "inflamação da córnea",
  },
  {
    nome: "Uveíte",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "inflamação uveal",
  },
  {
    nome: "Glaucoma",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "hipertensão ocular",
  },
  {
    nome: "Catarata",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "opacidade do cristalino",
  },
  {
    nome: "Luxação de cristalino",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "subluxação de cristalino",
  },
  {
    nome: "Atrofia progressiva de retina",
    especie: "AMBOS",
    categoria: "Oftálmica/Genética",
    sinonimos: "APR; PRA",
  },
  {
    nome: "Descolamento de retina",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "retina descolada",
  },
  {
    nome: "Entrópio",
    especie: "AMBOS",
    categoria: "Oftálmica",
    sinonimos: "inversão palpebral",
  },
  {
    nome: "Ectrópio",
    especie: "CANINO",
    categoria: "Oftálmica",
    sinonimos: "eversão palpebral",
  },
  {
    nome: "Prolapso da glândula da terceira pálpebra",
    especie: "CANINO",
    categoria: "Oftálmica",
    sinonimos: "cherry eye; olho de cereja",
  },
  {
    nome: "Doença periodontal",
    especie: "AMBOS",
    categoria: "Odontológica",
    sinonimos: "periodontite; doença dentária",
  },
  {
    nome: "Gengivite",
    especie: "AMBOS",
    categoria: "Odontológica",
    sinonimos: "inflamação gengival",
  },
  {
    nome: "Estomatite felina",
    especie: "FELINO",
    categoria: "Odontológica",
    sinonimos: "gengivoestomatite crônica felina",
  },
  {
    nome: "Lesão de reabsorção dentária felina",
    especie: "FELINO",
    categoria: "Odontológica",
    sinonimos: "reabsorção odontoclástica; FORL",
  },
  {
    nome: "Fratura dentária",
    especie: "AMBOS",
    categoria: "Odontológica",
    sinonimos: "dente fraturado",
  },
  {
    nome: "Abscesso dentário",
    especie: "AMBOS",
    categoria: "Odontológica",
    sinonimos: "abscesso periapical",
  },
  {
    nome: "Piometra",
    especie: "AMBOS",
    categoria: "Reprodutiva",
    sinonimos: "infecção uterina",
  },
  {
    nome: "Distocia",
    especie: "AMBOS",
    categoria: "Reprodutiva/Emergência",
    sinonimos: "parto difícil",
  },
  {
    nome: "Mastite",
    especie: "AMBOS",
    categoria: "Reprodutiva",
    sinonimos: "inflamação mamária",
  },
  {
    nome: "Pseudociese",
    especie: "CANINO",
    categoria: "Reprodutiva",
    sinonimos: "gravidez psicológica; falsa gestação",
  },
  {
    nome: "Criptorquidismo",
    especie: "AMBOS",
    categoria: "Reprodutiva/Congênita",
    sinonimos: "testículo retido",
  },
  {
    nome: "Orquite",
    especie: "CANINO",
    categoria: "Reprodutiva",
    sinonimos: "inflamação testicular",
  },
  {
    nome: "Epididimite",
    especie: "CANINO",
    categoria: "Reprodutiva",
    sinonimos: "inflamação do epidídimo",
  },
  {
    nome: "Anemia hemolítica imunomediada",
    especie: "AMBOS",
    categoria: "Hematológica/Imunomediada",
    sinonimos: "AHIM; IMHA",
  },
  {
    nome: "Trombocitopenia imunomediada",
    especie: "AMBOS",
    categoria: "Hematológica/Imunomediada",
    sinonimos: "TIM; ITP",
  },
  {
    nome: "Anemia não regenerativa",
    especie: "AMBOS",
    categoria: "Hematológica",
    sinonimos: "anemia arregenerativa",
  },
  {
    nome: "Anemia regenerativa",
    especie: "AMBOS",
    categoria: "Hematológica",
    sinonimos: "anemia regenerativa",
  },
  {
    nome: "Coagulação intravascular disseminada",
    especie: "AMBOS",
    categoria: "Hematológica/Emergência",
    sinonimos: "CID",
  },
  {
    nome: "Hemofilia",
    especie: "AMBOS",
    categoria: "Hematológica/Genética",
    sinonimos: "distúrbio de coagulação",
  },
  {
    nome: "Lúpus eritematoso sistêmico",
    especie: "CANINO",
    categoria: "Imunomediada",
    sinonimos: "LES",
  },
  {
    nome: "Poliartrite imunomediada",
    especie: "CANINO",
    categoria: "Imunomediada/Ortopédica",
    sinonimos: "PIM",
  },
  {
    nome: "Linfoma",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "linfossarcoma",
  },
  {
    nome: "Mastocitoma",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "tumor de mastócitos",
  },
  {
    nome: "Osteossarcoma",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "tumor ósseo maligno",
  },
  {
    nome: "Hemangiossarcoma",
    especie: "CANINO",
    categoria: "Oncológica",
    sinonimos: "HSA",
  },
  {
    nome: "Carcinoma de células escamosas",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "CCE",
  },
  {
    nome: "Tumor mamário",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "neoplasia mamária",
  },
  {
    nome: "Melanoma",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "melanoma maligno",
  },
  {
    nome: "Sarcoma de tecidos moles",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "STM",
  },
  {
    nome: "Fibrossarcoma",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "sarcoma fibroso",
  },
  {
    nome: "Sarcoma de aplicação felino",
    especie: "FELINO",
    categoria: "Oncológica",
    sinonimos: "sarcoma associado à injeção",
  },
  {
    nome: "Adenocarcinoma intestinal",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "câncer intestinal",
  },
  {
    nome: "Carcinoma de tireoide",
    especie: "AMBOS",
    categoria: "Oncológica",
    sinonimos: "neoplasia tireoidiana",
  },
  {
    nome: "Insulinoma",
    especie: "CANINO",
    categoria: "Oncológica/Endócrina",
    sinonimos: "tumor de células beta",
  },
  {
    nome: "Feocromocitoma",
    especie: "AMBOS",
    categoria: "Oncológica/Endócrina",
    sinonimos: "tumor adrenal",
  },
  {
    nome: "Tumor de bexiga",
    especie: "AMBOS",
    categoria: "Oncológica/Urinária",
    sinonimos: "carcinoma urotelial; carcinoma de células transicionais",
  },
  {
    nome: "Tumor cerebral",
    especie: "AMBOS",
    categoria: "Oncológica/Neurológica",
    sinonimos: "neoplasia intracraniana",
  },
  {
    nome: "Sepse",
    especie: "AMBOS",
    categoria: "Emergência/Infecciosa",
    sinonimos: "septicemia",
  },
  {
    nome: "Choque hipovolêmico",
    especie: "AMBOS",
    categoria: "Emergência",
    sinonimos: "hipovolemia grave",
  },
  {
    nome: "Choque anafilático",
    especie: "AMBOS",
    categoria: "Emergência/Imunológica",
    sinonimos: "anafilaxia",
  },
  {
    nome: "Golpe de calor",
    especie: "AMBOS",
    categoria: "Emergência",
    sinonimos: "hipertermia por calor",
  },
  {
    nome: "Intoxicação por chocolate",
    especie: "CANINO",
    categoria: "Toxicológica",
    sinonimos: "teobromina",
  },
  {
    nome: "Intoxicação por xilitol",
    especie: "CANINO",
    categoria: "Toxicológica",
    sinonimos: "xilitol",
  },
  {
    nome: "Intoxicação por etilenoglicol",
    especie: "AMBOS",
    categoria: "Toxicológica",
    sinonimos: "anticongelante",
  },
  {
    nome: "Intoxicação por rodenticida anticoagulante",
    especie: "AMBOS",
    categoria: "Toxicológica",
    sinonimos: "raticida anticoagulante",
  },
  {
    nome: "Intoxicação por permetrina",
    especie: "FELINO",
    categoria: "Toxicológica",
    sinonimos: "piretroide; permetrina em gatos",
  },
  {
    nome: "Intoxicação por paracetamol",
    especie: "FELINO",
    categoria: "Toxicológica",
    sinonimos: "acetaminofeno",
  },
  {
    nome: "Corpo estranho esofágico",
    especie: "AMBOS",
    categoria: "Gastrointestinal/Emergência",
    sinonimos: "obstrução esofágica",
  },
  {
    nome: "Hérnia diafragmática",
    especie: "AMBOS",
    categoria: "Respiratória/Trauma",
    sinonimos: "ruptura diafragmática",
  },
  {
    nome: "Hérnia umbilical",
    especie: "AMBOS",
    categoria: "Congênita/Cirúrgica",
    sinonimos: "hérnia de umbigo",
  },
  {
    nome: "Hérnia perineal",
    especie: "CANINO",
    categoria: "Cirúrgica",
    sinonimos: "hérnia do períneo",
  },
  {
    nome: "Síndrome de resposta inflamatória sistêmica",
    especie: "AMBOS",
    categoria: "Emergência",
    sinonimos: "SIRS",
  },
  {
    nome: "Ansiedade de separação",
    especie: "AMBOS",
    categoria: "Comportamental",
    sinonimos: "ansiedade por separação",
  },
  {
    nome: "Fobia a ruídos",
    especie: "AMBOS",
    categoria: "Comportamental",
    sinonimos: "medo de fogos; medo de trovões",
  },
  {
    nome: "Agressividade relacionada ao medo",
    especie: "AMBOS",
    categoria: "Comportamental",
    sinonimos: "agressão por medo",
  },
  {
    nome: "Eliminação inapropriada felina",
    especie: "FELINO",
    categoria: "Comportamental",
    sinonimos: "urina fora da caixa; fezes fora da caixa",
  },
];
